name: Auto Extract ZIP

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Extract ZIP to root
        run: |
          for file in *.zip; do
            unzip -o "$file"
          done

      - name: Remove ZIP
        run: rm -f *.zip

      - name: Commit extracted files
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add .
          git commit -m "Auto extract zip to root" || echo "No changes"
          git push
